[project]
name = "ShareFood"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "django>=6.0,<7.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "requests>=2.32",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-django>=4.14.0",
    "pylint",
    "pylint-django>=2.8.0",
]

[tool.pytest.ini_options]
pythonpath = ["src/ShareFood"]
DJANGO_SETTINGS_MODULE = "settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = ["tests"]


[tool.pylint.main]
load-plugins = ["pylint_django"]
django-settings-module = "settings"
init-hook = "import sys; sys.path.append('src/ShareFood')"
ignore = ["migrations"]

[tool.pylint."messages control"]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
]