# Generated by Django 6.0.6 on 2026-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Pasta'), ('canned', 'Canned Food'), ('drinks', 'Drinks'), ('sweets', 'Sweets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='district',
            field=models.CharField(choices=[('centru', 'Centru'), ('botanica', 'Botanica'), ('buiucani', 'Buiucani'), ('riscani', 'Riscani'), ('ciocana', 'Ciocana')], max_length=50),
        ),
    ]
