# Generated by Django 6.0.6 on 2026-09-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_foodlisting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(default='listings/default.jpg', upload_to='listings/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains & Pasta'), ('canned', 'Canned Food'), ('drinks', 'Drinks'), ('sweets', 'Sweets'), ('bakery', 'Bread & Bakery')], max_length=50),
        ),
    ]
